import {StyleSheet} from 'react-native';
import {FontFamilyMedium} from '../../Utils/AppContants';

export default StyleSheet.create({
  container: {
    marginTop: 20,
  },
  label: {
    fontSize: 14,
    marginBottom: 20,
    fontFamily: FontFamilyMedium,
  },
  row: {
    flexDirection: 'row',
    borderRadius: 100,
  },
  inputField: {
    width: '36%',
    height: 50,
    // backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: 'white',
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
    paddingLeft: 10,
  },
  inputFieldBlack: {
    width: '36%',
    height: 50,
    // backgroundColor: 'white',
    borderWidth: 0.5,
    borderColor: 'black',
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
    paddingLeft: 10,
  },
  textField: {
    width: '36%',
    height: 50,
    borderWidth: 1,
    borderColor: 'white',
    padding: 4,
    paddingTop: 15,
    color: 'white',
    fontFamily: FontFamilyMedium,
  },

  textFieldBlack: {
    width: '36%',
    height: 50,
    borderWidth: 1,
    borderColor: 'black',
    padding: 4,
    paddingTop: 15,
    paddingLeft: 10,
    color: 'black',
    fontFamily: FontFamilyMedium,
  },
  iconContainer: {
    width: '15%',
    // backgroundColor: 'white',
    alignSelf: 'center',
    alignItems: 'center',
    borderTopWidth: 0.5,
    borderBottomWidth: 1,
    borderColor: 'white',
    height: 50,
  },

  iconContainerBlack: {
    width: '15%',
    // backgroundColor: 'white',
    alignSelf: 'center',
    alignItems: 'center',
    borderTopWidth: 0.5,
    borderBottomWidth: 1,
    borderColor: 'black',
    height: 50,
  },
  iconContainerLast: {
    width: '15%',
    // backgroundColor: 'white',
    alignSelf: 'center',
    alignItems: 'center',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightWidth: 1,
    borderColor: 'white',
    height: 50,
    borderTopRightRadius: 100,
    borderBottomRightRadius: 100,
  },

  iconContainerLastBlack: {
    width: '15%',
    // backgroundColor: 'white',
    alignSelf: 'center',
    alignItems: 'center',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    borderRightWidth: 1,
    borderColor: 'black',
    height: 50,
    borderTopRightRadius: 100,
    borderBottomRightRadius: 100,
  },
  centerIcon: {
    width: 30,
    height: 30,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 10,
  },
});
